import { createFileRoute, Link } from "@tanstack/react-router";
import { useState, useEffect } from "react";
import { ArrowLeft, ShieldCheck, Lock, Eye, Sun, Moon } from "lucide-react";

export const Route = createFileRoute("/privacy")({
  head: () => ({
    meta: [
      { title: "Privacy Policy - SodaCraft Tamil" },
      {
        name: "description",
        content:
          "Official Privacy Policy of SodaCraft Tamil explaining how supporter information, payment tokens, and data privacy are secured.",
      },
    ],
  }),
  component: PrivacyPage,
});

function PrivacyPage() {
  const [theme, setTheme] = useState<"dark" | "light">("dark");

  useEffect(() => {
    const saved = localStorage.getItem("theme");
    if (saved === "light" || saved === "dark") setTheme(saved);
  }, []);

  const toggleTheme = () => {
    const next = theme === "dark" ? "light" : "dark";
    setTheme(next);
    localStorage.setItem("theme", next);
  };

  const isLight = theme === "light";

  return (
    <div
      className={`min-h-screen transition-colors duration-300 ${
        isLight ? "bg-slate-50 text-slate-800" : "bg-[oklch(0.12_0.02_260)] text-white"
      }`}
    >
      {/* Header */}
      <header
        className={`sticky top-0 z-30 border-b backdrop-blur-md px-4 sm:px-8 py-4 flex items-center justify-between ${
          isLight
            ? "bg-white/80 border-slate-200 shadow-sm"
            : "bg-[oklch(0.14_0.02_260)]/80 border-white/10"
        }`}
      >
        <div className="flex items-center gap-3">
          <Link
            to="/"
            className="p-2 rounded-xl bg-white/10 hover:bg-white/20 transition flex items-center gap-1.5 text-xs font-bold"
          >
            <ArrowLeft className="w-4 h-4" />
            <span>Home</span>
          </Link>
          <div className="h-4 w-px bg-white/15" />
          <h1 className="text-sm sm:text-base font-black tracking-tight flex items-center gap-2">
            <ShieldCheck className="w-4 h-4 text-emerald-400" />
            <span>Privacy & Policies</span>
          </h1>
        </div>

        <button
          type="button"
          onClick={toggleTheme}
          className="p-2 rounded-xl bg-white/10 hover:bg-white/20 transition"
          title="Toggle theme"
        >
          {isLight ? <Moon className="w-4 h-4" /> : <Sun className="w-4 h-4" />}
        </button>
      </header>

      {/* Content */}
      <main className="max-w-4xl mx-auto px-4 sm:px-6 py-10 sm:py-14 space-y-8">
        <div className="text-center space-y-2">
          <span className="text-xs font-bold uppercase tracking-wider text-emerald-400">
            Supporter Data Protection
          </span>
          <h2 className="text-2xl sm:text-3xl font-black">Privacy Policy & Security Standards</h2>
          <p className={`text-xs sm:text-sm ${isLight ? "text-slate-500" : "text-white/60"}`}>
            Last updated: September 2026 • SodaCraft Tamil Privacy Commitment
          </p>
        </div>

        <div
          className={`p-6 sm:p-8 rounded-3xl border shadow-xl space-y-6 text-sm leading-relaxed ${
            isLight ? "bg-white border-slate-200" : "bg-white/5 border-white/10"
          }`}
        >
          <section className="space-y-3">
            <h3 className="text-lg font-bold flex items-center gap-2 text-emerald-400">
              <Lock className="w-5 h-5" />
              <span>1. Information We Collect</span>
            </h3>
            <p>When you visit SodaCraft Tamil or submit a voluntary creator tip, we may collect:</p>
            <ul className="list-disc pl-5 space-y-1.5 opacity-90">
              <li>
                <strong>Supporter Profile:</strong> Your display name, optional email, and custom
                fan message.
              </li>
              <li>
                <strong>Transaction Identifier:</strong> Payment transaction ID generated by
                Razorpay or UPI confirmation for receipt verification.
              </li>
              <li>
                <strong>Technical Logs:</strong> Browser user agent and timestamp to prevent
                malicious abuse and protect the admin portal.
              </li>
            </ul>
          </section>

          <section className="space-y-3">
            <h3 className="text-lg font-bold flex items-center gap-2 text-emerald-400">
              <ShieldCheck className="w-5 h-5" />
              <span>2. How We Use Your Information</span>
            </h3>
            <ul className="list-disc pl-5 space-y-1.5 opacity-90">
              <li>To attribute and feature your name on the Live Stream / Support ticker.</li>
              <li>To generate and deliver your official digital Payment Receipt.</li>
              <li>To dispatch the automated WhatsApp verification notification to the creator.</li>
              <li>
                To accurately update the monthly SMP server and stream hardware goal progress.
              </li>
            </ul>
          </section>

          <section className="space-y-3">
            <h3 className="text-lg font-bold flex items-center gap-2 text-emerald-400">
              <Eye className="w-5 h-5" />
              <span>3. Payment Gateway Security (Razorpay)</span>
            </h3>
            <p>
              We <strong>NEVER</strong> store, process, or view your debit/credit card numbers,
              CVVs, net banking passwords, or UPI PINs. All financial transactions are processed
              directly via <strong>Razorpay Payment Gateway</strong> using bank-grade 256-bit SSL
              encryption and PCI-DSS Level 1 compliance.
            </p>
          </section>

          <section className="space-y-3">
            <h3 className="text-lg font-bold flex items-center gap-2 text-emerald-400">
              <ShieldCheck className="w-5 h-5" />
              <span>4. Third-Party Services</span>
            </h3>
            <p>Our website integrates with:</p>
            <ul className="list-disc pl-5 space-y-1.5 opacity-90">
              <li>
                <strong>Razorpay:</strong> Secure payment processing and verified webhooks.
              </li>
              <li>
                <strong>Google AdSense / Analytics:</strong> Creator monetization and aggregate
                traffic insights.
              </li>
              <li>
                <strong>WhatsApp:</strong> Direct creator messaging for receipt confirmations.
              </li>
            </ul>
          </section>

          <section className="space-y-3">
            <h3 className="text-lg font-bold flex items-center gap-2 text-emerald-400">
              <Lock className="w-5 h-5" />
              <span>5. Contact Our Privacy Officer</span>
            </h3>
            <p>
              If you wish to request deletion of your supporter name from the public leaderboard or
              have data privacy questions, email:
              <br />
              <strong className="text-emerald-400 font-mono">SodaCraftads@gmail.com</strong>
            </p>
          </section>
        </div>

        {/* Footer Navigation */}
        <div className="flex flex-wrap items-center justify-center gap-6 pt-4 text-xs opacity-75">
          <Link to="/" className="hover:text-emerald-400 transition">
            Home
          </Link>
          <span>•</span>
          <Link to="/support" className="hover:text-emerald-400 transition">
            Support Creator
          </Link>
          <span>•</span>
          <Link to="/terms" className="hover:text-emerald-400 transition">
            Terms & Conditions
          </Link>
          <span>•</span>
          <Link to="/refund" className="hover:text-emerald-400 transition">
            Refund Policy
          </Link>
          <span>•</span>
          <Link to="/contact" className="hover:text-emerald-400 transition">
            Contact Us
          </Link>
        </div>
      </main>
    </div>
  );
}
